name: CI for different Linux distributions

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        cmake -DENABLE_REGRESSION_TEST:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH:=python3 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        cmake --build . -- -j$(nproc)
    - name: regression test (UK based)
      run: |
        ctest --tests-regex regressiontest_UK_100th --verbose
    - name: regression test (US based)
      run: |
        ctest --tests-regex regressiontest_US_based --verbose

  test-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_image: ["fedora:latest", "debian:10", "archlinux/base", "ubuntu:bionic", "centos:7", "opensuse/tumbleweed", "alpine:latest"]
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_dependencies.sh
    - name: build
      run: |
        mkdir build && cd build
        cmake -DENABLE_REGRESSION_TEST:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH:=python3 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        cmake --build . -- -j$(nproc)
    - name: regression test (UK based)
      run: |
        ctest --tests-regex regressiontest_UK_100th --verbose
    - name: regression test (US based)
      run: |
        ctest --tests-regex regressiontest_US_based --verbose
