name: CI for macOS

on: push

jobs:
  test:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_macos_dependencies.sh
    - name: build
      run: |
        mkdir build && cd build
        cmake -DENABLE_REGRESSION_TEST:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH:=/usr/local/bin/python3 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        cmake --build . -- -j`nproc`
    - name: regression test (UK based)
      run: |
        ctest --tests-regex regressiontest_UK_100th --verbose
    - name: regression test (US based)
      run: |
        ctest --tests-regex regressiontest_US_based --verbose
