name: CI for Windows

on: push

jobs:
  windows:
    name: Windows build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          md build
          cd build
          cmake -DENABLE_REGRESSION_TEST:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
          cmake --build .
      - name: regression test (UK based)
        run: |
          ctest --tests-regex regressiontest_UK_100th --verbose
      - name: regression test (US based)
        run: |
          ctest --tests-regex regressiontest_US_based --verbose
